### ISSUE TITLE
Why did you use Express?

### ISSUE THREAD

**Issue by noctivityinc** [sonufrienko/microservice#11]
@sonufrienko thanks for this boilerplate but I find it odd that it's Express-based given that you linked to it from your benchmark of Fastify vs. Express.  Why did you set this up with Express instead of Fastify?

**Comment by sonufrienko** [comment]
Hi @noctivityinc 

I like **Fastify** for
- performance
- http2
- awesome features out of the box

**Express** I like for
- huge community (used by +5M apps)
- security & well tested in battle
- number of middlewares

Also, consider using serverless Functions to focus on business logic only.

**Comment by noctivityinc** [comment]
So is your go to fastify or express for new projects now a days?  Which do
YOU prefer?

**Comment by sonufrienko** [comment]
@noctivityinc I prefer Express :smile: 
But new projects I prefer to start with Serverless Architecture.

**Comment by noctivityinc** [comment]
Well when the guy who wrote the article on using fastify over express uses
express, that makes my decision easier!
